server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/apple?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
  redis:
    database: 0 #数据库索引
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 1024
        max-idle: 200 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
        max-wait: 10000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    timeout: 10000 # 连接超时时间（毫秒）
    block-when-exhausted: true

  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    suffix: .html
    prefix: classpath:/templates/
    content-type: text/html
    check-template-location: true
    enabled: true